version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: algo-duo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: algo-duo
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build: .
    container_name: algo-duo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/algo-duo?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
    volumes:
      - ./src:/app/src
      - /app/node_modules

  # Code execution service (using Docker-in-Docker)
  code-executor:
    image: docker:dind
    container_name: algo-duo-executor
    privileged: true
    restart: always
    ports:
      - "2375:2375"
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - docker_data:/var/lib/docker

volumes:
  mongodb_data:
  docker_data: